### ISSUE TITLE
Request result incomplete

### ISSUE THREAD

**Issue by QingwenL** [RebirthLee/mysql_udf_http_golang#1]
![image](https://user-images.githubusercontent.com/26764303/70974485-d36c2880-20e2-11ea-8e4c-6620c7fd46e3.png)

**Comment by 2rebi** [comment]
Plz, Show me your mysql(or mariadb) config, computing spec, server application environment and more detail.

Your comment is not detailed enough. Give me more informations.

**Comment by 2rebi** [comment]
If you don't comment. I will close this issue after 7 days.
